### ISSUE TITLE
Did you stop working on this?

### ISSUE THREAD

**Issue by The-Rock-21** [embr-dev/GameHub#3]

**Comment by Russell2259** [comment]
GameHub has had some server issues that I have been working on and off to fix. I have been working on other projects and have been busy with school. All in all gamehub is dead for now but I have hopes of bringing it back.

**Comment by hey122112** [comment]
> GameHub has had some server issues that I have been working on and off to fix. I have been working on other projects and have been busy with school. All in all gamehub is dead for now but I have hopes of bringing it back.

but still you have't worked on this to me this showed me you either lazy or not caring at all

**Comment by Russell2259** [comment]
> > GameHub has had some server issues that I have been working on and off to fix. I have been working on other projects and have been busy with school. All in all gamehub is dead for now but I have hopes of bringing it back.
> 
> but still you have't worked on this to me this showed me you either lazy or not caring at all

I have no motivation or reason to continue working on a project that does not interest me. I am also occupied with things in my personal life and am unable to work on all of my unfinished projects and please everyone. Feel free to check out another site I have helped with called [polaris](https://github.com/Skoolgq/Polaris) with a game collection similar to Gamehub's.
